on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: hello
        name: Testing Hello World Sample Code
        uses: anauskadutta/sample2@v1
        with:
          who-to-greet: 'World!!!'
